const { UNLEASH_URL, UNLEASH_TOKEN } = process.env

const headers = {
	Authorization: UNLEASH_TOKEN || '',
	'Content-Type': 'application/json',
}

export const createProject = async (name: string) =>
	(
		await fetch(`${UNLEASH_URL}/api/admin/projects`, {
			method: 'POST',
			headers,
			body: JSON.stringify({
				name,
				description: 'Project to hammer',
				defaultStickiness: 'default',
				mode: 'open',
				changeRequestEnvironments: [],
			}),
		})
	).json() as Promise<{ id: string }>

export const deleteProject = async (name: string) =>
	(
		await fetch(`${UNLEASH_URL}/api/admin/projects/${name}`, {
			headers,
			method: 'DELETE',
		})
	).ok

export const createToken = async (
	environment: string,
	projects: string[] = ['*'],
	prefix = 'hammer',
) => {
	const username = `${prefix}_${crypto.randomUUID()}`
	await fetch(`${UNLEASH_URL}/api/admin/api-tokens`, {
		method: 'POST',
		headers,
		body: JSON.stringify({
			username,
			type: 'CLIENT',
			environment,
			projects,
		}),
	})

	return username
}

export const deleteToken = async (name: string) =>
	(
		await fetch(`${UNLEASH_URL}/api/admin/api-tokens/${name}`, {
			headers,
			method: 'DELETE',
		})
	).ok

export const getTokens = async () =>
	(
		await fetch(`${UNLEASH_URL}/api/admin/api-tokens`, {
			headers,
		})
	).json()

export const createFlag = async (project: string, prefix = 'hammer'): Promise<[string, string]> => {
	const name = `${prefix}_${crypto.randomUUID()}`
	await fetch(`${UNLEASH_URL}/api/admin/projects/${project}/features`, {
		method: 'POST',
		headers,
		body: JSON.stringify({
			type: 'release',
			name,
			description: 'Generated by unleash-sdk-hammer',
			impressionData: true,
		}),
	})
	return [project, name]
}

export const deleteFlag = async (project: string, id: string) =>
	(
		await fetch(`${UNLEASH_URL}/api/admin/projects/${project}/features/${id}`, {
			headers,
			method: 'DELETE',
		})
	).ok
